/**
 * k6 shared helpers for vortex-backend performance tests.
 *
 * Usage:
 *   import { BASE_URL, createIntent, checkResponse } from '../lib/helpers.js';
 */

import http from 'k6/http';
import { check } from 'k6';

/** Base URL — override via K6_BASE_URL env var for CI. */
export const BASE_URL = __ENV.K6_BASE_URL || 'http://localhost:4000';

/** Standard JSON POST headers. */
export const JSON_HEADERS = { 'Content-Type': 'application/json' };

/**
 * A canonical valid intent body that passes all DTO validation.
 * Uses the same field values as the e2e test suite.
 */
export const INTENT_BODY = {
  user: 'GBSV2XLBHGMRQRMQJM7HKNJLEFAGRJKQFSLPZWQBQ5WMTUPNR4T7YHF',
  srcChain: 'ethereum',
  srcTokenAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
  srcTokenSymbol: 'USDC',
  srcTokenDecimals: 6,
  srcAmount: '1000000',
  dstTokenContract: 'CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA',
  dstTokenSymbol: 'USDC',
  dstTokenDecimals: 7,
  minDstAmount: '9900000',
};

/** Quote request body — no auth required. */
export const QUOTE_BODY = {
  srcChain: 'ethereum',
  srcTokenSymbol: 'USDC',
  srcAmount: '1000000',
  dstTokenSymbol: 'USDC',
};

/**
 * Seeded solver public addresses (derived from SEED_SOLVER_SECRETS in solvers.seed.ts).
 */
export const SOLVER_ADDRESSES = {
  ALPHA: 'GA4GQI32ROYRZSN3G4PWKXUIZLPSBNLWRT65DI6WRC2VT3E7KLME4MNT',
  BETA: 'GCAEQSSB42DM4EZW7BFHEAJKR5LJGTRWJMFJLLZQS5YOHTEJNTHVJKWM',
  GAMMA: 'GDZJ3QYCWXDSOP6CUCGQISOL65P4HH47XJT6UZAUJKF6V46XY66CASJN',
};

/**
 * Well-known user address for cancel intent tests.
 * Matches the keypair whose cancel signature is stored in FIXTURES.
 */
export const USER_ADDR = 'GCK6BSLBOJISE4YW3VX7I3RA7L3GO7WIQDF73RMMVV6ZTFWO2VA3XTK2';

/**
 * Pre-computed Ed25519 fixture signatures for the lifecycle scenario.
 *
 * All signatures are over a canonical intent whose ID is FIXTURE_INTENT_ID.
 * Generated by test/perf/k6/scripts/generate-fixtures.mjs — do not edit by hand.
 * Regenerate with: npm run perf:gen-fixtures
 *
 * Message format:
 *   accept: "accept:<intentId>:<solver>"
 *   fill:   "fill:<intentId>:<solver>"
 *   cancel: "cancel:<intentId>"
 */
export const FIXTURE_INTENT_ID = '00000000-0000-4000-8000-000000000001';

export const FIXTURES = {
  /** ALPHA solver accepts the fixture intent. */
  acceptAlpha: {
    solver: SOLVER_ADDRESSES.ALPHA,
    signature: 'u7YPCLI+aKJfdLw8BJUPE8CW8YQq989CH9mFFTJeOuRWgTVBkZZk5SeK3rI4VKl9wbtVqbDcrKadE7jvkHnNDg==',
  },
  /** ALPHA solver fills the fixture intent. */
  fillAlpha: {
    solver: SOLVER_ADDRESSES.ALPHA,
    fillAmount: '995000',
    signature: '5Gw1MFZj8F14EFK8xdOGO3cC7ohU1R1HnYydg30wJyY2L6hU0RHBmxPBf18THz5YwcMLVJIOugUXRL98IvIBAA==',
  },
  /** User cancels the fixture intent. */
  cancel: {
    user: USER_ADDR,
    signature: 'SDHCdKasMTauzVroc52sv7dSSbstdKJHDKsuJYMxG8o77On2zsO1BcUcTzuvBS4uTougKK82E1mlXoj7IRIjBA==',
  },
};

/**
 * POST a new intent and return the parsed response body.
 *
 * @param {object} [extraBody] - fields to merge into INTENT_BODY
 * @returns {{ intentId: string, state: string } | null}
 */
export function createIntent(extraBody = {}) {
  const res = http.post(
    `${BASE_URL}/api/v1/intents`,
    JSON.stringify({ ...INTENT_BODY, ...extraBody }),
    { headers: JSON_HEADERS },
  );
  if (res.status !== 201) return null;
  try {
    return JSON.parse(res.body);
  } catch {
    return null;
  }
}

/**
 * Assert a k6 response has the expected status and a parseable JSON body.
 *
 * @param {import('k6/http').RefinedResponse} res
 * @param {string} label - human-readable label shown in k6 output
 * @param {number} [expectedStatus=200]
 * @returns {boolean}
 */
export function checkResponse(res, label, expectedStatus = 200) {
  return check(res, {
    [`${label} status=${expectedStatus}`]: (r) => r.status === expectedStatus,
    [`${label} body=json`]: (r) => {
      try {
        JSON.parse(r.body);
        return true;
      } catch {
        return false;
      }
    },
  });
}

/**
 * Quick health probe — returns true if /health responds 200.
 * Used in setup() to bail out fast if the server isn't running.
 */
export function isServerHealthy() {
  const res = http.get(`${BASE_URL}/health`);
  return res.status === 200;
}
