import type { components, paths } from "./generated/api-types";

export type { components, paths };
type Schemas = components["schemas"];

export class VortexApiError extends Error {
  constructor(readonly status: number, readonly body: unknown) {
    super(`Vortex API ${status}: ${typeof body === "string" ? body : JSON.stringify(body)}`);
  }
}

/**
 * Typed REST client over the OpenAPI-generated types (`paths`,
 * `components`) regenerated by `npm run generate:client`.
 */
export class VortexRestClient {
  constructor(
    private readonly baseUrl: string,
    private readonly fetchImpl: typeof fetch = fetch,
  ) {}

  /** Low-level typed request for any documented path. */
  async request<T>(method: string, path: keyof paths | string, body?: unknown): Promise<T> {
    const res = await this.fetchImpl(`${this.baseUrl.replace(/\/$/, "")}${path}`, {
      method,
      headers: body === undefined ? undefined : { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const text = await res.text();
    const parsed = text ? JSON.parse(text) : undefined;
    if (!res.ok) throw new VortexApiError(res.status, parsed);
    return parsed as T;
  }

  getIntent(id: string) {
    return this.request<Record<string, unknown>>("GET", `/api/v1/intents/${encodeURIComponent(id)}`);
  }

  getAuctionPrice(id: string) {
    return this.request<{
      intentId: string;
      currentDstAmount: string;
      acceptedDstAmount?: string;
      timestamp: number;
    }>("GET", `/api/v1/intents/${encodeURIComponent(id)}/auction`);
  }

  listOpenIntents() {
    return this.request<{ intents: Array<Record<string, unknown>> }>("GET", "/api/v1/intents/open");
  }

  quote(body: Schemas["QuoteRequestDto"]) {
    return this.request<Schemas extends { QuoteResponseDto: infer Q } ? Q : unknown>("POST", "/api/v1/intents/quote", body);
  }

  accept(id: string, body: Schemas["AcceptIntentDto"]) {
    return this.request<Record<string, unknown>>("POST", `/api/v1/intents/${encodeURIComponent(id)}/accept`, body);
  }

  fill(id: string, body: Schemas["FillIntentDto"]) {
    return this.request<Record<string, unknown>>("POST", `/api/v1/intents/${encodeURIComponent(id)}/fill`, body);
  }

  cancel(id: string, body: Schemas["CancelIntentDto"]) {
    return this.request<Record<string, unknown>>("POST", `/api/v1/intents/${encodeURIComponent(id)}/cancel`, body);
  }
}
